export const items = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "food-1.jfif",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "غداء",
    imgUrl: "food-2.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وصف العشاء",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "food-3.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "food-1.jfif",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف الغداء",
    price: "50 جنيه",
    category: "غداء",
    imgUrl: "food-2.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وصف العشاء",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "food-3.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة سناك",
    description: "وصف السناك",
    price: "50 جنيه",
    category: "سناك",
    imgUrl: "food-2.jpg",
  },
];
